<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<title>Payment Failed</title>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-md-6" align="center">
			<span class="alerticon" style="display: block; margin-top: 20px"><img src="http://s22.postimg.org/ulf9c0b71/error.png" alt="checkmark" /></span>
			<h2>Sorry!</h2>
			Your payment is failed, please check your payment detail and try again.<br>
		</div>
	</div>
</div>
</body>
</html>