<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js"></script>
    <title>Redirect Payment - Loading...</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
</head>
<body>
	<h3 align="center">Loading...</h3>
    <form name="adyenForm" action="<?=$url?>" method="post">
	<?php
	foreach ($params as $key => $value){
	    echo '        <input type="hidden" name="' .htmlspecialchars($key,   ENT_COMPAT | ENT_HTML401 ,'UTF-8'). 
	                                   '" value="' .htmlspecialchars($value, ENT_COMPAT | ENT_HTML401 ,'UTF-8') . '" />' ."\n" ;
	}
	?>
    <input type="submit" value="Submit" style="display: none" />
    </form>
    <script type="text/javascript">
    	$(function(){
    		$("form").submit();
    	});
    </script>
</body>
</html>