<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script>
		var payment_method = $('input[name=payment_method]:checked').val();
	</script>
	<title>Payment Method</title>

<style>
.input-hidden {
  position: absolute;
  left: -9999px;
}

input[type=radio]:checked + label>img {
  
  box-shadow: 0 0 3px 3px #090;
}

/* Stuff after this is only to make things more pretty */
input[type=radio] + label>img {
  border: 0px solid #444;
  
  
}

body {
	background-color: #eee;
}


/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 95%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
}

</style>

</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12" align="center">
			<!-- <span class="alerticon" style="display: block; margin-top: 20px"><img src="http://s22.postimg.org/i5iji9hv1/check.png" alt="checkmark" /></span> -->
			<h1><img src="<?=$url?>dashboard/assets/panel/dist/img/logo-tunehotels.jpg"></h1>
			<h5 class="alert alert-success" style="font-weight:bold;padding-top:20px"><span class="glyphicon glyphicon-credit-card"></span> PLEASE SELECT PAYMENT METHOD</h5>
			<form method="put" action="<?=$url?>v1/payment/set-redirect" class="form-horizontal">
			<input type="hidden" name="booking_id" value="<?php echo $this->request->get('booking_id') ?>"/>
			<input type="hidden" name="grand_total" value="<?php echo $this->request->get('grand_total') ?>"/>
			<input type="hidden" name="currency" value="<?php echo $this->request->get('currency') ?>"/>
			<input type="hidden" name="discount_name" value="<?php echo $this->request->get('discount_name') ?>"/>
			<input type="hidden" name="discount_value" value="<?php echo $this->request->get('discount_value') ?>"/>
			<div class="row">
			<?php 
				$payment = json_decode($payment_method);
				$no = 0;
				foreach ($payment as $key => $pay) { $no++;?>
				<div class="col-xs-6" style="padding-top:15px">
			    
			    <input type="radio" class="input-hidden" id="payment-<?php echo $no;?>" name="payment_method" value="<?php echo $pay->payment_gateway;?>,<?php echo $pay->post_url;?>,<?php echo $pay->merchant_account;?>,<?php echo $pay->skin;?>,<?php echo $pay->title;?>" required="required"/>
			    <label for="payment-<?php echo $no;?>">
			    <img src="http://th.tbvlabs.com/dashboard/assets/uploads/payments/<?php echo $pay->image_url;?>?<?=time()?>" style="width:80px;" align=center>
			    </label>
			    <?php //echo $pay->title;?>
			  </div>
			<?php } ?>
			</div>
						</div>
						<div class="col-xs-12">
					<br><br>
					<button type="submit" class="btn btn-danger btn-lg btn-block"><span class="glyphicon glyphicon-play-circle"></span> NEXT</button>
					<button type="button" class="btn btn-danger btn-lg btn-block" onclick="return popitup('http://th-prod.tbvlabs.com/dashboard/test.php')"> POPUP 1</button>
					<button type="button" class="btn btn-danger btn-lg btn-block" id="myBtn">POPUP 2</button>

					</div>
			</form>

	</div>
</div>


<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">x</span>
    <p>Some text in POPUP..</p>
    <div id=content></div>
  </div>

</div>

<script language="javascript" type="text/javascript">
<!--
function popitup(url) {
	
	var radioButtons = document.getElementsByName("payment_method");
	var pg;
	for (var i = 0; i < radioButtons.length; i++) {
		if (radioButtons[i].checked) {
			//console.log("radioButton " + i + ": " + radioButtons[i].value);
			pg = radioButtons[i].value;
		}
	}	
	
	//alert(pg);
	newurl = url + '?pg=' + pg;
	newwindow=window.open(newurl,'name','height=400,width=450');
	if (window.focus) {newwindow.focus()}
	return false;
}





// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on the button, open the modal 
btn.onclick = function() {
	
var radioButtons1 = document.getElementsByName("payment_method");
	var pg1;
	for (var i = 0; i < radioButtons1.length; i++) {
		if (radioButtons1[i].checked) {
			//console.log("radioButton " + i + ": " + radioButtons[i].value);
			pg1 = radioButtons1[i].value;
		}
	}	
	
	document.getElementById('content').innerHTML = "test "+pg1;
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}

//var payment_method = document.getElementByName('payment_method');



// -->
</script>

</body>
</html>