<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<title>Payment Success</title>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-md-6" align="center">
			<span class="alerticon" style="display: block; margin-top: 20px"><img src="http://s22.postimg.org/i5iji9hv1/check.png" alt="checkmark" /></span>
			<h2>Thank You!</h2>
			You successfuly booked tune hotel room<br>
			<h4>Booking Detail</h4>
			<table class="table table-striped table-hover">
				<tbody>
					<tr>
						<td>Transaction Code</td>
						<td>:</td>
						<td><?=$trans_id?></td>
					</tr>
					<tr>
						<td>Confirmation Id</td>
						<td>:</td>
						<td><?=$confirmation_id?></td>
					</tr>
					<tr>
						<td>Name</td>
						<td>:</td>
						<td><?=$first_name." ".$last_name?></td>
					</tr>
					<tr>
						<td>Email</td>
						<td>:</td>
						<td><?=$email?></td>
					</tr>
					<tr>
						<td>Start</td>
						<td>:</td>
						<td><?=$booking_range_start?></td>
					</tr>
					<tr>
						<td>End</td>
						<td>:</td>
						<td><?=$booking_range_end?></td>
					</tr>
					<tr>
						<td>Amount</td>
						<td>:</td>
						<td><?=$grand_total." ".$total_curency?></td>
					</tr>
					<tr>
						<td>Room Type</td>
						<td>:</td>
						<td><?=$room_type?></td>
					</tr>
					<?php if (!empty($addons) && $addons!='"null"'): ?>
					<tr>
						<td colspan="3"><strong>Addons</strong></td>
					</tr>
					<?php foreach ($addons as $key => $value): ?>
					<tr>
						<td colspan="2"><?=$value['service_name']?></td>
						<td><?=$value['qty']?></td>
					</tr>
					<?php endforeach ?>	
					<?php endif ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
</body>
</html>