<p>Hello <?=$name?>,</p>
This is your booking detail
<hr>
<p>Transaction ID : <strong><?=$trans_id?></strong></p>
<table class="table table-hover">
	<thead>
		<th>
			<td colspan="2"></td>
			<td><?=$currency?></td>
		</th>
	</thead>
	<tbody>
		<tr>
			<td>Room Rate</td>
			<td>:</td>
			<td align="right"><?=$total_room_rate?></td>
		</tr>
		<tr>
			<td>Addon</td>
			<td>:</td>
			<td align="right"><?=$total_addon?></td>
		</tr>
		<tr>
			<td>Sub Total</td>
			<td>:</td>
			<td align="right"><?=$subtotal?></td>
		</tr>
		<tr>
			<td>Tax</td>
			<td>:</td>
			<td align="right"><?=$tax_fees?></td>
		</tr>
		<tr>
			<td>Total</td>
			<td>:</td>
			<td align="right"><?=$total?></td>
		</tr>
	</tbody>
</table>