<p><?=$firstname?>,</p>
<p>Your hotel is successfully reserved, below is reserve detail </p>
<table class="table">
	<tbody>
		<tr>
			<td>Confirmation Id</td>
			<td>:</td>
			<td><?=$confirmation_id?></td>
		</tr>
		<tr>
			<td>Order Number</td>
			<td>:</td>
			<td><?=$order_no?></td>
		</tr>
		<tr>
			<td>Booking Start</td>
			<td>:</td>
			<td><?=$start_date?></td>
		</tr>
		<tr>
			<td>Booking End</td>
			<td>:</td>
			<td><?=$end_date?></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>:</td>
			<td><?=$status?></td>
		</tr>
	</tbody>
</table>
